In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3,4])

In [3]:
type(a)

numpy.ndarray

In [4]:
a.dtype

dtype('int64')

In [5]:
 a.size

5

In [6]:
a.ndim

1

In [7]:
a.shape

(5,)

In [8]:
b = np.array([3.1,11.02,6.2,213.2,5.2])

In [9]:
b

array([  3.1 ,  11.02,   6.2 , 213.2 ,   5.2 ])

In [10]:
type(b)

numpy.ndarray

In [11]:
b.dtype

dtype('float64')

In [12]:
c=np.array([20,1,2,3,4])
c

array([20,  1,  2,  3,  4])

In [14]:
c[0]=100
c

array([100,   1,   2,   3,   4])

In [15]:
c[4]=0
c

array([100,   1,   2,   3,   0])

In [16]:
d=c[1:4]
d

array([1, 2, 3])

In [17]:
c[3:5]=300,400
c

array([100,   1,   2, 300, 400])

#### Vector Addition

In [18]:
u=np.array([1,0])
v=np.array([0,1])
z=u+v
z

array([1, 1])

##### Vector Subtraction

In [19]:
u=np.array([1,0])
v=np.array([0,1])
z=u-v
z

array([ 1, -1])

#### Vector Multiplication

In [21]:
y=np.array([1,2])
z=2*y
z

array([2, 4])

#### Hadamard Product

In [22]:
u=np.array([1,2])
v=np.array([3,2])
z=u*v
z

array([3, 4])

 #### Dot Product

In [24]:
u=np.array([1,2])
v=np.array([3,1])
result=np.dot(u,v)
result

5

#### Broadcasting - Adding a Constant to a Numpy Array

In [26]:
u=np.array([1,2,3,-1])
z=u+1
z

array([2, 3, 4, 0])

#### Universal Functions

In [27]:
a=np.array([1,-1,1,-1])
mean_a=a.mean()
mean_a

0.0

In [28]:
b=np.array([1,-2,3,4,5])
b.max()

5

In [29]:
b.min()

-2

In [30]:
b.mean()

2.2

In [31]:
b.std()

2.4819347291981715

In [32]:
np.pi

3.141592653589793

In [33]:
x=np.array([0,np.pi/2,np.pi])
y=np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [36]:
np.linspace(-2,2,9) # 9 Evenly space values starting at -2 and ending at 2

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])